import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/globals.css';
import Header from '@/components/header/Header';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Vc Inspector',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <Header />
<<<<<<< HEAD
          <div className="container mx-auto">{children}</div>
=======
          {children}
>>>>>>> 1ce96a7 (add logos and links on navigation bar)
        </>
      </body>
    </html>
  );
}
