name: Continuous Deployment

on:
  push:
    branches:
      - main
jobs:
  gen-doc:
    name: Generate inspector documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install

      - name: Generate html with Typedoc
        run: pnpm typedoc
