name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  install-check-test:
    name: Install, check format, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install

      - name: Check linting
        run: pnpm lint
        continue-on-error: true

      - name: Check prettier formatting
        run: pnpm prettier:check
        continue-on-error: true

      - name: Check typescript types
        run: pnpm types
        continue-on-error: true

      - name: Check production build
        run: pnpm build
        continue-on-error: true

      - name: Cypress component test
        uses: cypress-io/github-action@v6
        with:
          component: true
        continue-on-error: true

      - name: Cypress component integration
        uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          start: npx serve@latest out
